TOPDIR = ..

include $(TOPDIR)/makefile.config

OBJECTS= error.$(OBJ) d_io.$(OBJ) d_glob.$(OBJ) strutil.$(OBJ) strio.$(OBJ) \
        d_delay.$(OBJ) compare.$(OBJ) d_slash.$(OBJ)

OUTPUT = $(LIBDIR)/misc.$(LIB)

include $(TOPDIR)/makefile.lib
