TOPDIR = ..

include $(TOPDIR)/makefile.config

OBJECTS = clipper.$(OBJ) matrix.$(OBJ) rod.$(OBJ) \
	draw.$(OBJ) instance.$(OBJ) points.$(OBJ) setup.$(OBJ) \
	globvars.$(OBJ) interp.$(OBJ)

OUTPUT = $(LIBDIR)/3d.$(LIB)

include $(TOPDIR)/makefile.lib
