#this file must be included in all makefiles right after TOPDIR is defined
#reads the build settings and corrects unusable configurations

include $(TOPDIR)/config

#version defines

D1XMAJOR = 0
D1XMINOR = 40

CFLAGS += -DD1XMAJOR=\"$(D1XMAJOR)\" -DD1XMINOR=\"$(D1XMINOR)\"

CFLAGS += -D DESCENT_DATA_PATH=\"$(DESCENT_DATA_PATH)\"

DESTDIR = $(TOPDIR)/$(DESTINATION_DIR)

LIBDIR = $(TOPDIR)/lib/

#use general include directory

CFLAGS += -I$(TOPDIR)/include

#always support netip code

SUPPORTS_NET_IP = 1

#enabled dependant features

ifdef WGL_IO
OGL = 1
endif

ifdef GLX_IO
OGL = 1
GGI = 1
GII_XWIN = 1
GII_INPUT = 1
endif

ifdef SDLGL_IO
OGL = 1
SDL_INPUT = 1
SDL = 1
endif

ifdef SDL_IO
SDL_INPUT = 1
SDL_VIDEO = 1
SDL = 1
endif

ifdef SDL_AUDIO
SDL = 1
endif

ifdef SVGALIB_IO
SVGALIB_INPUT = 1
SVGALIB_VIDEO = 1
SVGALIB = 1
endif

ifdef GGI_IO
GII_INPUT = 1
GGI_VIDEO = 1
GGI = 1
endif

#defines for features

ifndef MONO
CFLAGS += -DNMONO
endif

ifndef NETWORK
undef SUPPORTS_NET_IP
endif

ifdef SUPPORTS_NET_IP
CFLAGS += -DSUPPORTS_NET_IP
endif

ifdef NETWORK
CFLAGS += -DNETWORK
endif

ifdef RELEASE
CFLAGS += -DRELEASE 
endif

ifdef SHAREWARE
NO_RL2 = 1
CFLAGS += -DSHAREWARE
endif

ifdef NO_ASM
CFLAGS += -DNO_ASM
endif

ifdef D1XD3D
CFLAGS += -DD1XD3D
endif

ifdef NOERROR
CFLAGS += -Werror
endif

ifdef MAKE_EDITOR
NO_RL2 = 1
CFLAGS += -DEDITOR -I.
endif

ifdef SDLGL_IO
CFLAGS += -DSDL_GL
endif

ifdef GLX_IO
CFLAGS += -DGLX_VIDEO
endif

ifdef OGL
ifdef OGL_RUNTIME
CFLAGS += -DOGL_RUNTIME_LOAD
endif
CFLAGS += -I$(TOPDIR)/arch/ogl -DOGL
endif

ifdef ENV_CYGWIN
ENV_MINGW32 = 1
else
ifdef ENV_MINGW32
CRAPPY_SHELL = 1
endif
endif

ifdef ENV_MINGW32
CFLAGS += -I$(TOPDIR)/arch/win32 -D__WINDOWS__
NASM = nasmw -f win32
endif

ifdef ENV_MSVC
CRAPPY_SHELL = 1
OBJ = obj
ARC = lib
CC=cl
CFLAGS += -nologo -c -W3 -Zi -I$(TOPDIR)/arch/win32 -D__WINDOWS__
ifdef DEBUG
CFLAGS += -MDd -Od
else
ifdef DEBUGABLE
CFLAGS += -MDd -Od -DNDEBUG
else
CFLAGS += -MD -Ox -DNDEBUG
endif
endif
else
# definitions for gcc
OBJ = o
ARC = a
CC = gcc
CXX = g++
ifdef DEBUG
CFLAGS += -c -Wall $(OPTFLAGS) -funsigned-char
else
CFLAGS += -c -Wall $(OPTFLAGS) -funsigned-char -DNDEBUG
ifndef DEBUGABLE
CFLAGS += -fomit-frame-pointer
endif
endif
ifdef MINGW_EXTRA
CFLAGS += -I$(MINGW_EXTRA)/include
LFLAGS += -L$(MINGW_EXTRA)/lib
endif
ifdef ENV_CYGWIN
CFLAGS += -mno-cygwin
LFLAGS += -mno-cygwin
endif
ifdef PROFILE
CFLAGS += -p
LFLAGS += -p
endif
endif

ifdef ENV_LINUX
CFLAGS += -I$(TOPDIR)/arch/linux -D__LINUX__
ifdef GII_XWIN
CFLAGS += -DGII_XWIN
endif
ifdef SDL
ifdef STATICSDL
CFLAGS += -D_SDL_STATIC_LIB
endif
endif
ifdef GLIBC
CFLAGS += -D_REENTRANT
endif
NASM = nasm -f elf -d__LINUX__
ifdef HAVENETIPX
CFLAGS += -DHAVE_NETIPX_IPX_H
endif
endif

ifdef SVGALIB
CFLAGS += -D__SVGALIB__
ifdef SVGALIB_INPUT
CFLAGS += -I$(TOPDIR)/arch/linux/svgalib -DSVGALIB_INPUT
endif
ifdef SVGALIB_VIDEO
CFLAGS += -DSVGALIB_VIDEO
endif
endif

ifdef GGI
CFLAGS += -D__GGI__
ifdef GGI_VIDEO
CFLAGS += -DGGI_VIDEO
endif
ifdef GII_INPUT
CFLAGS += -I$(TOPDIR)/arch/linux/ggi -DGII_INPUT
endif
endif

ifdef SDL
CFLAGS += -D__SDL__
ifdef SDL_INPUT
CFLAGS += -I$(TOPDIR)/arch/sdl -DSDL_INPUT
endif
ifdef SDL_VIDEO
CFLAGS += -DSDL_VIDEO
endif
ifdef SDL_AUDIO
CFLAGS += -DSDL_AUDIO
endif
endif

