#default makefile for libraries

CPPFLAGS= $(CFLAGS)

all: $(SUBDIRS) $(OUTPUT)

include $(TOPDIR)/makefile.rules

$(OUTPUT): $(LIBDIR) $(OBJDIR) $(OBJECTS_TARGETS) $(OBJECTS_DONT_LINK_TARGETS) $(RESOURCES_TARGETS)
	ar rcs $(OUTPUT) $(OBJECTS_TARGETS) $(RESOURCES_TARGETS)

$(LIBDIR):
ifeq ($(ENV_MINGW32),1)
	mkdir $(subst /,\,$(LIBDIR))
else
	mkdir $(LIBDIR)
endif

#dependancy generation

ALLOBJECTS = $(OBJECTS_TARGETS) $(OBJECTS_DONT_LINK_TARGETS)
DEPFILES=$(subst .$(OBJ),.d,$(ALLOBJECTS))

$(OBJDIR)/%.d: %.c
	-mkdir $(OBJDIR)
	$(CC) $(CFLAGS) $(E_CFLAGS) -MM $< >> $@

$(OBJDIR)/%.d: %.cpp
	-mkdir $(OBJDIR)
	$(CC) $(CFLAGS) $(E_CFLAGS) -MM $< >> $@
	
ifneq ($(DEPFILES),)
-include $(DEPFILES)
endif

clean:
ifneq ($(OUTPUT),)
	-rm -r $(OBJDIR)
	-rm $(OUTPUT)
endif
	$(CLEANSUBS)
