CFLAGS= -g -O2 -Wall -Werror `sdl-config --cflags` -I../include -DSTANDALONE
LDFLAGS=`sdl-config --libs`

OBJS=mveplay.o mvelib.o mve_audio.o ../mem/mem.o ../misc/error.o ../misc/args.o console.o ../misc/strutil.o ../misc/strio.o

mveplay: ${OBJS}

clean:
	rm -f mveplay ${OBJS}
