/*
THE COMPUTER CODE CONTAINED HEREIN IS THE SOLE PROPERTY OF PARALLAX
SOFTWARE CORPORATION ("PARALLAX").  PARALLAX, IN DISTRIBUTING THE CODE TO
END-USERS, AND SUBJECT TO ALL OF THE TERMS AND CONDITIONS HEREIN, GRANTS A
ROYALTY-FREE, PERPETUAL LICENSE TO SUCH END-USERS FOR USE BY SUCH END-USERS
IN USING, DISPLAYING,  AND CREATING DERIVATIVE WORKS THEREOF, SO LONG AS
SUCH USE, DISPLAY OR CREATION IS FOR NON-COMMERCIAL, ROYALTY OR REVENUE
FREE PURPOSES.  IN NO EVENT SHALL THE END-USER USE THE COMPUTER CODE
CONTAINED HEREIN FOR REVENUE-BEARING PURPOSES.  THE END-USER UNDERSTANDS
AND AGREES TO THE TERMS HEREIN AND ACCEPTS THE SAME BY USE OF THIS FILE.  
COPYRIGHT 1993-1998 PARALLAX SOFTWARE CORPORATION.  ALL RIGHTS RESERVED.
*/
// 
// Auto-generated include file 
// Generated by MAKE from INFERNO.INI settings 
// 

#define NEWDEMO			//Demo is always IN 

//#define EDITOR			//Editor is OUT 
//#define RELEASE			//This IS a release version 
//#define ARCADE			//Arcade (ATW) code is OUT 
//#define DEMO_ONLY		//Game is playable 
//#define NDEBUG	1		//NDEBUG is ON
//#ifdef NDEBUG
//#define NMONO                           //NMONO is ON if NDEBUG is ON
//#endif
//#define _MARK_ON		//MARKS are OFF 
//#define PASSWORD		//PASSWORD is OFF 
//#define STORE_DEMO 1	//STORE_DEMO is OFF 

#define PIGGY_USE_PAGING 1		//Don't use paging from pig file

//#define DEST_SAT 1		// Not building for Destination Saturn (OEM version)
//#define REQUIRE_CD 1	// Doesn't require a CD in drive 
//#define USE_CD 1		// Doesn't use a CD in drive
//#define ROCKWELL_CODE 1	// Rockwell psuedo shareware 
//#define COMPACT_SEGS 1		// Not building for Destination Saturn (OEM version) 
//#define NETWORK 1               // Not building for Destination Saturn (OEM version)

//#define QUICKSTART 1
