/* $Id: vers_id.h,v 1.5 2003-11-27 00:21:04 btb Exp $ */
//
// Auto-generated include file [used to be]
// Generated by MAKE from INFERNO.INI settings
//


#ifndef _VERS_ID
#define _VERS_ID

#ifndef VERSION
# define VERSION
#endif

#define VERSION_TYPE	"Full Version"
#define DESCENT_VERSION "D2X " VERSION
#define D2X_IVER (D2XMAJOR*10000+D2XMINOR*100+D2XMICRO)

#endif /* _VERS_ID */
