/* $Id: vers_id.h,v 1.4 2003-10-10 09:36:35 btb Exp $ */
//
// Auto-generated include file [used to be]
// Generated by MAKE from INFERNO.INI settings
//


#ifndef _VERS_ID
#define _VERS_ID

#define VERSION_TYPE	"Full Version"
#define DESCENT_VERSION "D2X " VERSION
#define D2X_IVER (D2XMAJOR*10000+D2XMINOR*100+D2XMICRO)

#endif /* _VERS_ID */
