TOPDIR = ../../..

OBJECTS =	\
	d3denum.$(OBJ)	\
	d3dframe.$(OBJ)	\
	d3dmath.$(OBJ)	\
	d3dtextr.$(OBJ)	\
	d3dutil.$(OBJ)	\
	userdlg.$(OBJ)	\
	ddenum.$(OBJ)

OUTPUT = $(LIBDIR)d3dframe.$(ARC)

include $(TOPDIR)/makefile.lib
