TOPDIR = ..

#include $(TOPDIR)/makefile.config

OBJECTS = \
 med.$(OBJ) eglobal.$(OBJ) mine.$(OBJ) curves.$(OBJ) \
 kcurve.$(OBJ) khelp.$(OBJ) ksegsel.$(OBJ) kbuild.$(OBJ) kview.$(OBJ) \
 kmine.$(OBJ) seguvs.$(OBJ) ksegsize.$(OBJ) ksegmove.$(OBJ) ktmap.$(OBJ) \
 kfuncs.$(OBJ) autosave.$(OBJ) group.$(OBJ) texture.$(OBJ) fixseg.$(OBJ) \
 eobject.$(OBJ) elight.$(OBJ) texpage.$(OBJ) objpage.$(OBJ) medmisc.$(OBJ) \
 medsel.$(OBJ) kgame.$(OBJ) info.$(OBJ) medwall.$(OBJ) eswitch.$(OBJ) \
 medrobot.$(OBJ) meddraw.$(OBJ) segment.$(OBJ) ehostage.$(OBJ) centers.$(OBJ) \
 func.$(OBJ)

OUTPUT = $(LIBDIR)editor.$(ARC)

E_CFLAGS = -I../main -I../include/editor -DEDITOR

include $(TOPDIR)/makefile.lib
