#include <physfs.h>
#include "dxxsconf.h"

#ifndef DXX_ENABLE_wrap_PHYSFS_write
#define DXX_ENABLE_wrap_PHYSFS_write	DXX_HAVE_POISON_VALGRIND
#endif

#if DXX_ENABLE_wrap_PHYSFS_write
extern "C" {
	DXX_VG_DECLARE_EXTERN_C(PHYSFS_write);
	DXX_VG_DECLARE_EXTERN_C(PHYSFS_writeSBE16);
	DXX_VG_DECLARE_EXTERN_C(PHYSFS_writeSBE32);
	DXX_VG_DECLARE_EXTERN_C(PHYSFS_writeSLE16);
	DXX_VG_DECLARE_EXTERN_C(PHYSFS_writeSLE32);
	DXX_VG_DECLARE_EXTERN_C(PHYSFS_writeULE16);
	DXX_VG_DECLARE_EXTERN_C(PHYSFS_writeULE32);
}

DXX_VG_DEFINE_WRITE(PHYSFS_writeSBE16, PHYSFS_sint16);
DXX_VG_DEFINE_WRITE(PHYSFS_writeSBE32, PHYSFS_sint32);
DXX_VG_DEFINE_WRITE(PHYSFS_writeSLE16, PHYSFS_sint16);
DXX_VG_DEFINE_WRITE(PHYSFS_writeSLE32, PHYSFS_sint32);
DXX_VG_DEFINE_WRITE(PHYSFS_writeULE16, PHYSFS_uint16);
DXX_VG_DEFINE_WRITE(PHYSFS_writeULE32, PHYSFS_uint32);

#endif
