.\"                                      Hey, EMACS: -*- nroff -*-
.\" First parameter, NAME, should be all caps
.\" Second parameter, SECTION, should be 1-8, maybe w/ subsection
.\" other parameters are allowed: see man(7), man(1)
.TH HOGCREATE 1 "July 10, 2003"
.\" Please adjust this date whenever revising the manpage.
.\"
.\" Some roff macros, for reference:
.\" .nh        disable hyphenation
.\" .hy        enable hyphenation
.\" .ad l      left justify
.\" .ad b      justify to both left and right margins
.\" .nf        disable filling
.\" .fi        enable filling
.\" .br        insert line break
.\" .sp <n>    insert n+1 empty lines
.\" for manpage-specific macros, see man(7)
.SH NAME
hogcreate \- Creates an HOG archive using all the files in the current
directory.
.SH SYNOPSIS
.B hogcreate
.RI filename.hog
.br
.SH DESCRIPTION
This manual page documents briefly the
.B hogcreate
command.
This manual page was written for the Debian distribution
because the original program does not have a manual page.
.PP
.B hogcreate
is an utility to create HOG files, like that found in the DESCENT II
videogame and played by the D2X package.

HOG archives are files with a .hog extension, and contains all of the data
which constitutes a DESCENT II's level.

You'll find some HOG files as part of the Descent II datafiles.
.SH SEE ALSO
.BR hogextract (1),
.BR mvlextract (1),
.BR mveplayer (1).
.SH AUTHOR
The command was first created by Josh Cogliati in 1999, then modified by
Bradley Bell in 2002 for use with the D2X package.

This manual page was written by Paolo Ulivi <pulivi@libero.it>,
for the Debian GNU/Linux system (but may be used by others).
