/* conf.h.  Generated by configure.  */
/* conf.h.in.  Generated from configure.ac by autoheader.  */
/* modified to use with MSVC */

/* Define to 1 if the system has the type `struct timespec'. */
#define HAVE_STRUCT_TIMESPEC 0

/* Define to 1 if the system has the type `struct timeval'. */
#define HAVE_STRUCT_TIMEVAL 1
