name: Package - Linux

on:
  #push:
  #  branches: [ master ]

  #pull_request:
  #  branches: [ master ]

  workflow_dispatch:

jobs:
  linux:
    name: Linux AppImages
    runs-on: ubuntu-20.04
    steps:
      - name: Clone Repository
        uses: actions/checkout@v3
        
      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install gcc-10 g++-10
          sudo apt-get install -y scons libsdl2-dev libsdl2-image-dev libsdl2-mixer-dev libphysfs-dev
          
      - name: Configure and build
        run: scons -j`nproc` opengl=1 sdl2=1 sdlmixer=1
        env:
          CC:   gcc-10
          CXX:  g++-10
        
      - name: Package AppImage
        run: ./contrib/packaging/linux/build_package.sh
        
      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: linux
          path: '*.AppImage'
