name: Package - Linux
on:
  workflow_dispatch:
  workflow_call:

jobs:
  build:
    name: GCC 13 / Ubuntu 24.04
    runs-on: "ubuntu-latest"
    container:
      image: "ubuntu:24.04"
    steps:
      - name: Clone Repository
        uses: actions/checkout@v4

      - name: Install build tools and dependencies
        run: |
          apt-get update
          apt install -y \
              gcc-13 g++-13 python3 scons \
              libsdl1.2-dev libsdl-image1.2-dev libsdl-mixer1.2-dev libphysfs-dev libpng-dev

      - name: Configure and Build
        run: scons -j`nproc`
        env:
          CC: gcc-13
          CXX: g++-13

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: linux-loose
          path: |
            build/d1x-rebirth/d1x-rebirth
            build/d2x-rebirth/d2x-rebirth

  package:
    name: Package AppImage
    needs: build
    runs-on: "ubuntu:latest"
    steps:
      - name: Install AppImage dependencies
        run: apt-get update && apt-get install -y libfuse2 wget curl

      - name: Clone Repository
        uses: actions/checkout@v4

      - name: Download build
        uses: actions/download-artifact@v4
        with:
          name: linux-loose

      - name: Package AppImage
        run: |
          mv linux-loose/build .
          rmdir linux-loose
          contrib/packaging/linux/build_package.sh
