name: Package - Linux
on:
  workflow_dispatch:
  workflow_call:

concurrency:
  group: linux-${{ github.workflow_ref }}-${{ github.ref }}
  cancel-in-progress: true
jobs:
  package:
    name: GCC 15
    runs-on: ubuntu-26.04
    steps:
      - name: Clone Repository
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          persist-credentials: false

      - name: Install Dependencies
        run: >
          sudo apt-get update

          sudo apt install -y
          bubblewrap
          gcc-15 g++-15
          python3
          scons
          libsdl2-dev
          libsdl2-image-dev
          libsdl2-mixer-dev
          libphysfs-dev
          libpng-dev
          libgl-dev
          libglu1-mesa-dev

      - name: Collect architecture
        id: architecture
        run: |
          printf 'uname_m=%s\n' "$(uname -m)" >> "$GITHUB_OUTPUT"

      - name: Update gamecontrollerdb.txt
        run: >-
          curl --fail --silent --show-error --location
          --output contrib/gamecontrollerdb.txt
          https://raw.githubusercontent.com/gabomdq/SDL_GameControllerDB/master/gamecontrollerdb.txt
          || true

      - name: Configure and Build
        run: >
          mkdir -p build

          sudo sysctl -w kernel.apparmor_restrict_unprivileged_userns=0

          nproc="$(nproc)"

          bwrap
          --unshare-net
          --unshare-pid
          --unshare-user
          --ro-bind / /
          --dev /dev
          --bind /tmp /tmp
          --bind "$PWD/build" "$PWD/build"
          --
          scons
          "-j$nproc"
          -k
          CXX=g++-15
          sdl2=1
          "CXXFLAGS=-flto=$(( $nproc + 1 / 2 ))"

      - name: Upload SConf log
        if: ${{ !cancelled() }}
        uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # v7.0.1
        with:
          name: "SConf-Linux-${{ steps.architecture.outputs.uname_m }}"
          path: 'build/config.log'

      - name: Install AppImage Requirements
        run: sudo apt-get install -y libfuse2 wget curl

      - name: Package
      # No bubblewrap sandbox for this step, since:
      # - as an unprivileged user, `--unshare-user` is a prerequisite for any
      # other `--unshare-NS`
      #
      # - `--unshare-net` would prevent `build_package.sh` downloading the tool
      # to create the AppImage.  The download of the AppImage helper tool could
      # be split out and run outside the `--unshare-net` sandbox.  However, due
      # to the next point, this does not help.
      #
      # - the downloaded tool uses FUSE to mount its embedded libraries, and
      # using FUSE requires running the setuid `fusermount`.  `fusermount` does
      # not elevate properly inside the unprivileged user namespace.  Thus,
      # FUSE would fail under `--unshare-user`, causing the downloaded tool to
      # fail.
      #
      # - `--unshare-pid` is not significant on its own.
      #
      # - Binding the build directory as read-only causes the AppImage tool to
      # fail to create its directory structure.  This might be possible to fix
      # with a different invocation of the tool, but was not attempted, since
      # unprivileged `bwrap` breaks FUSE, and privileged `bwrap` without a user
      # namespace would run the process as root inside the sandbox.
        run: ./contrib/packaging/linux/build_package.sh
        env:
          rebirth_uname_m: ${{ steps.architecture.outputs.uname_m }}

      - name: Upload Artifact
        uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # v7.0.1
        with:
          name: "DXX-Rebirth-Linux-AppImage-${{ steps.architecture.outputs.uname_m }}"
          path: 'D*X-Rebirth.AppImage'

      - name: Check header includes
        run: >
          nproc="$(nproc)"

          bwrap
          --unshare-net
          --unshare-pid
          --unshare-user
          --ro-bind / /
          --dev /dev
          --bind /tmp /tmp
          --bind "$PWD/build" "$PWD/build"
          --
          scons
          "-j$nproc"
          -k
          CXX=g++-15
          sdl2=1
          "CXXFLAGS=-flto=$(( $nproc + 1 / 2 ))"
          check_header_includes=1
          build/{common,d1x-rebirth,d2x-rebirth}/check_header_includes
