name: Package-SDL1.2-Windows

on:
  #push:
  #  branches: [ package ]

  #pull_request:
  #  branches: [ master ]

  workflow_dispatch:
    inputs:
      tag:
        description: 'The tag used for release'
        default: ''
        required: false
      type:
        description: 'The type of release to be published (supported values: stable, prerelease)'
        default: ''
        required: false
      name:
        description: 'The title of the release'
        default: ''
        required: false
jobs:          
  windows:
    name: Windows
    runs-on: windows-2019
    
    defaults:
      run:
        shell: msys2 {0}
    
    steps:
      - name: Setup MSYS2
        uses: msys2/setup-msys2@v2
        with:
          msystem: MINGW64
          update: true
          install: >-
            git
            zip
            base-devel 
            mingw-w64-x86_64-toolchain
            mingw-w64-x86_64-scons
            mingw-w64-x86_64-pkgconf
            mingw-w64-x86_64-SDL
            mingw-w64-x86_64-SDL_image
            mingw-w64-x86_64-SDL_mixer
            mingw-w64-x86_64-physfs
        
      - name: Clone repository
        uses: actions/checkout@v4
              
      - name: Configure and build
        run: scons -j2 sdlmixer=1
      
      - name: Package
        run: ./contrib/packaging/windows/build_package.sh

      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: windows
          path: '*.zip'
