name: Package - Linux
on:
  workflow_dispatch:
  workflow_call:

concurrency:
  group: linux-${{ github.workflow_ref }}-${{ github.ref }}
  cancel-in-progress: true
jobs:
  package:
    name: GCC 15
    runs-on: ubuntu-26.04
    steps:
      - name: Clone Repository
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          persist-credentials: false

      - name: Install Dependencies
        run: >
          sudo apt-get update

          sudo apt install -y
          gcc-15 g++-15
          python3
          scons
          libsdl2-dev
          libsdl2-image-dev
          libsdl2-mixer-dev
          libphysfs-dev
          libpng-dev
          libgl-dev
          libglu1-mesa-dev

      - name: Collect architecture
        id: architecture
        run: |
          printf 'uname_m=%s\n' "$(uname -m)" >> "$GITHUB_OUTPUT"

      - name: Update gamecontrollerdb.txt
        run: >-
          curl --fail --silent --show-error --location
          --output contrib/gamecontrollerdb.txt
          https://raw.githubusercontent.com/gabomdq/SDL_GameControllerDB/master/gamecontrollerdb.txt
          || true

      - name: Configure and Build
        run: >
          nproc="$(nproc)"

          scons
          "-j$nproc"
          -k
          CXX=g++-15
          sdl2=1
          "CXXFLAGS=-flto=$(( $nproc + 1 / 2 ))"

      - name: Upload SConf log
        if: ${{ !cancelled() }}
        uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # v7.0.1
        with:
          name: "SConf-Linux-${{ steps.architecture.outputs.uname_m }}"
          path: 'build/config.log'

      - name: Install AppImage Requirements
        run: sudo apt-get install -y libfuse2 wget curl

      - name: Package
        run: ./contrib/packaging/linux/build_package.sh
        env:
          rebirth_uname_m: ${{ steps.architecture.outputs.uname_m }}

      - name: Upload Artifact
        uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # v7.0.1
        with:
          name: "DXX-Rebirth-Linux-AppImage-${{ steps.architecture.outputs.uname_m }}"
          path: 'D*X-Rebirth.AppImage'

      - name: Check header includes
        run: >
          nproc="$(nproc)"

          scons
          "-j$nproc"
          -k
          CXX=g++-15
          sdl2=1
          "CXXFLAGS=-flto=$(( $nproc + 1 / 2 ))"
          check_header_includes=1
          build/{common,d1x-rebirth,d2x-rebirth}/check_header_includes
