name: Package - Linux
on:
  workflow_dispatch:
  workflow_call:

jobs:
  package:
    name: GCC 13
    runs-on: ubuntu-latest
    container:
      image: "ubuntu:24.04"
    steps:
      - name: Clone Repository
        uses: actions/checkout@v4

      - name: Install build tools and dependencies
        run: |
          apt-get update
          apt install -y \
              gcc-13 g++-13 python3 scons \
              libsdl1.2-dev libsdl-image1.2-dev libsdl-mixer1.2-dev libphysfs-dev libpng-dev \
              libfuse2 wget curl

      - name: Configure and Build
        run: scons -j`nproc`
        env:
          CC: gcc-13
          CXX: g++-13

      - name: Package
        run: ./contrib/packaging/linux/build_package.sh

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: linux
          path: '*.zip'
