name: Package - Windows
on:
  workflow_dispatch:
  workflow_call:

jobs:
  package:
    name: MINGW64
    runs-on: windows-2022
    defaults:
      run:
        shell: msys2 {0}
    steps:
      - name: Setup MSYS2
        uses: msys2/setup-msys2@v2
        with:
          msystem: MINGW64
          update: true
          install: >-
            git
            zip
            base-devel
            mingw-w64-x86_64-toolchain
            mingw-w64-x86_64-scons
            mingw-w64-x86_64-pkgconf
            mingw-w64-x86_64-SDL
            mingw-w64-x86_64-SDL_image
            mingw-w64-x86_64-SDL_mixer
            mingw-w64-x86_64-physfs

      - name: Clone Repository
        uses: actions/checkout@v4
        with:
          path: src

      - name: Collect architecture
        id: architecture
        run: |
          printf 'uname_m=%s\n' "$(uname -m)" >> "$GITHUB_OUTPUT"

      - name: Configure and Build
        working-directory: src
        run: scons -j`nproc`

      - name: Package
        working-directory: src
        run: ./contrib/packaging/windows/build_package.sh -o .. -z ''

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: "DXX-Rebirth-Windows-${{ steps.architecture.outputs.uname_m }}"
          path: 'D*X-Rebirth/'
