name: Create version tag
on:
  push:
    branches:
      - master
      - main

jobs:
  tag:
    name: Create tag
    runs-on: ubuntu-22.04
    permissions:
      contents: write
    steps:
      - name: Bump version and push tag
        id: tag_version
        uses: mathieudutour/github-tag-action@v6.2
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}

      - name: Create release
        uses: release.yml
        with:
          tag_name: ${{ steps.tag_version.outputs.new_tag }}
